name: Node.js CI

on:
  push:
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Specify Node.js versions to test against

    steps:
    - uses: actions/checkout@v4 # Checkout the repository code
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4 # Setup Node.js environment
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache npm dependencies for faster builds
    - name: Install dependencies
      run: npm ci # Install project dependencies
    - name: Run tests
      run: npm test # Execute the test script defined in package.json